# Generated by Django 5.1.3 on 2024-11-06 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='doctor_DB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FnD', models.CharField(blank=True, max_length=100, null=True)),
                ('LnD', models.CharField(blank=True, max_length=100, null=True)),
                ('UsD', models.CharField(blank=True, max_length=100, null=True)),
                ('PsD', models.CharField(blank=True, max_length=100, null=True)),
                ('EmD', models.EmailField(blank=True, max_length=100, null=True)),
                ('CpD', models.CharField(blank=True, max_length=100, null=True)),
                ('DoD', models.IntegerField(blank=True, null=True)),
                ('CnD', models.CharField(blank=True, max_length=100, null=True)),
                ('CtD', models.CharField(blank=True, max_length=100, null=True)),
                ('AeD', models.CharField(blank=True, max_length=100, null=True)),
                ('GnD', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=20)),
                ('PhD', models.IntegerField(blank=True, null=True)),
                ('ImD', models.ImageField(blank=True, null=True, upload_to='docimage')),
                ('BiD', models.TextField(blank=True, max_length=100, null=True)),
                ('StD', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=20)),
            ],
        ),
    ]
