# Generated by Django 5.1.3 on 2024-11-06 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor_db',
            name='DoD',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
