# Generated by Django 5.1 on 2024-11-15 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medapp', '0002_alter_doctor_db_dod'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor_db',
            old_name='AeD',
            new_name='Dcountry',
        ),
        migrations.RenameField(
            model_name='doctor_db',
            old_name='CnD',
            new_name='Dcpswd',
        ),
        migrations.RenameField(
            model_name='doctor_db',
            old_name='CpD',
            new_name='Ddepartment',
        ),
        migrations.RenameField(
            model_name='doctor_db',
            old_name='EmD',
            new_name='Demail',
        ),
        migrations.RenameField(
            model_name='doctor_db',
            old_name='CtD',
            new_name='Dgender',
        ),
        migrations.RenameField(
            model_name='doctor_db',
            old_name='FnD',
            new_name='Dhospital',
        ),
        migrations.RenameField(
            model_name='doctor_db',
            old_name='LnD',
            new_name='Dname',
        ),
        migrations.RenameField(
            model_name='doctor_db',
            old_name='PhD',
            new_name='Dphone',
        ),
        migrations.RenameField(
            model_name='doctor_db',
            old_name='ImD',
            new_name='Dpic',
        ),
        migrations.RenameField(
            model_name='doctor_db',
            old_name='PsD',
            new_name='Dpswd',
        ),
        migrations.RenameField(
            model_name='doctor_db',
            old_name='UsD',
            new_name='Dusername',
        ),
        migrations.RemoveField(
            model_name='doctor_db',
            name='DoD',
        ),
        migrations.RemoveField(
            model_name='doctor_db',
            name='GnD',
        ),
        migrations.AddField(
            model_name='doctor_db',
            name='Ddob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
