# Generated by Django 5.1 on 2024-11-25 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medapp', '0003_rename_aed_doctor_db_dcountry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor_db',
            name='StD',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=20, null=True),
        ),
    ]
