# Generated by Django 5.1.3 on 2024-11-26 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medapp', '0004_alter_doctor_db_std'),
    ]

    operations = [
        migrations.CreateModel(
            name='appoint_DB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Acountry', models.CharField(blank=True, max_length=100, null=True)),
                ('Ahospital', models.CharField(blank=True, max_length=100, null=True)),
                ('Adepartment', models.CharField(blank=True, max_length=100, null=True)),
                ('Adoctor', models.CharField(blank=True, max_length=100, null=True)),
                ('AppointmentNO', models.IntegerField(blank=True, null=True)),
                ('Abookingdate', models.IntegerField(blank=True, null=True)),
                ('Aname', models.CharField(blank=True, max_length=100, null=True)),
                ('Aphone', models.IntegerField(blank=True, null=True)),
                ('Agender', models.CharField(blank=True, max_length=100, null=True)),
                ('Ablood', models.CharField(blank=True, max_length=100, null=True)),
                ('Adiabeties', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Blog_DB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Btitle', models.CharField(blank=True, max_length=100, null=True)),
                ('Bimage', models.ImageField(blank=True, null=True, upload_to='Blog Image')),
                ('Bcontent', models.TextField(blank=True, max_length=300, null=True)),
                ('Bwriter', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='hospital_DB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HosName', models.CharField(blank=True, max_length=100, null=True)),
                ('HosDepartment', models.CharField(blank=True, max_length=100, null=True)),
                ('HosDoctor', models.CharField(blank=True, max_length=100, null=True)),
                ('HosCountry', models.CharField(blank=True, max_length=100, null=True)),
                ('HosNumber', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='doctor_db',
            name='StD',
        ),
        migrations.AlterField(
            model_name='doctor_db',
            name='Ddob',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
