# Generated by Django 5.1.3 on 2024-11-26 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medapp', '0005_appoint_db_blog_db_hospital_db_remove_doctor_db_std_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital_db',
            name='HosNumber',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
