# Generated by Django 5.1.3 on 2024-11-26 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medapp', '0006_alter_hospital_db_hosnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appoint_db',
            name='Abookingdate',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='appoint_db',
            name='Aphone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='doctor_db',
            name='Ddob',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='doctor_db',
            name='Dphone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
