# Generated by Django 5.1.3 on 2024-11-27 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medapp', '0007_alter_appoint_db_abookingdate_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='doctor_DB',
        ),
    ]
