# Generated by Django 5.1.3 on 2024-11-27 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medapp', '0008_delete_doctor_db'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor_DB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('D_hospital', models.CharField(blank=True, max_length=100, null=True)),
                ('D_department', models.CharField(blank=True, max_length=100, null=True)),
                ('D_name', models.CharField(blank=True, max_length=100, null=True)),
                ('D_phone', models.CharField(blank=True, max_length=100, null=True)),
                ('D_email', models.CharField(blank=True, max_length=100, null=True)),
                ('D_image', models.ImageField(blank=True, null=True, upload_to='doctor photo')),
                ('D_age', models.CharField(blank=True, max_length=100, null=True)),
                ('D_gender', models.CharField(blank=True, max_length=100, null=True)),
                ('D_country', models.CharField(blank=True, max_length=100, null=True)),
                ('D_bio', models.TextField(blank=True, max_length=300, null=True)),
                ('D_contract', models.BooleanField(default=False, null=True)),
            ],
        ),
    ]
