# Generated by Django 5.1 on 2024-11-29 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medapp', '0009_doctor_db'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospital_db',
            old_name='HosDepartment',
            new_name='HosEmail',
        ),
        migrations.RenameField(
            model_name='hospital_db',
            old_name='HosDoctor',
            new_name='HosWebsite',
        ),
    ]
