# Generated by Django 5.1 on 2024-11-29 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medapp', '0010_rename_hosdepartment_hospital_db_hosemail_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department_DB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DepName', models.CharField(blank=True, max_length=100, null=True)),
                ('DepTime', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
