# Generated by Django 5.1.3 on 2024-12-01 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medapp', '0011_department_db'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pharmacy_DB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Medname', models.CharField(blank=True, max_length=100, null=True)),
                ('Medimage', models.ImageField(blank=True, null=True, upload_to='pharmacy image')),
                ('Medprice', models.CharField(blank=True, max_length=100, null=True)),
                ('Medqty', models.CharField(blank=True, max_length=100, null=True)),
                ('Medmanufacture', models.CharField(blank=True, max_length=100, null=True)),
                ('Meduses', models.TextField(blank=True, max_length=300, null=True)),
                ('Medside', models.TextField(blank=True, max_length=300, null=True)),
                ('Meddesc', models.TextField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
