# Generated by Django 5.1.3 on 2024-12-10 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medapp', '0012_pharmacy_db'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country_DB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CON_name', models.CharField(blank=True, max_length=100, null=True)),
                ('CON_image', models.ImageField(blank=True, null=True, upload_to='Country photo')),
            ],
        ),
    ]
