# Generated by Django 5.1 on 2025-01-18 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medapp', '0013_country_db'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital_db',
            name='HosDept1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hospital_db',
            name='HosDept2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hospital_db',
            name='HosDept3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hospital_db',
            name='HosDept4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hospital_db',
            name='HosDept5',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hospital_db',
            name='HosDept6',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
