# Generated by Django 5.1.3 on 2025-01-23 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medapp', '0014_hospital_db_hosdept1_hospital_db_hosdept2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appoint_db',
            name='Atime',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
