# Generated by Django 5.1.3 on 2025-01-23 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medapp', '0017_alter_appoint_db_atime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appoint_db',
            name='Atime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
