# Generated by Django 5.1.3 on 2025-01-23 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medapp', '0018_alter_appoint_db_atime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appoint_db',
            name='Abookingdate',
        ),
    ]
