# Generated by Django 5.1.3 on 2025-01-04 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contactform_DB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_enquiry', models.CharField(blank=True, max_length=100, null=True)),
                ('email_enquiry', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_enquiry', models.CharField(blank=True, max_length=100, null=True)),
                ('sub_enquiry', models.CharField(blank=True, max_length=100, null=True)),
                ('message_enquiry', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
