# Generated by Django 5.1 on 2025-01-18 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MedMeet', '0003_otp_delete_userotp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otp',
            old_name='otp',
            new_name='otp_code',
        ),
        migrations.RemoveField(
            model_name='otp',
            name='is_verified',
        ),
    ]
