# Generated by Django 5.1 on 2025-02-02 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedMeet', '0006_otp_remove_verificationcode_user_delete_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expired', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='OTP',
        ),
    ]
