# Generated by Django 5.1 on 2025-02-03 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedMeet', '0007_otpverification_delete_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignUpDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='OTPVerification',
        ),
    ]
