# Generated by Django 5.1 on 2025-02-03 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedMeet', '0008_signupdb_delete_otpverification'),
    ]

    operations = [
        migrations.CreateModel(
            name='appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_Country', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_Hospital', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_Department', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_Doctor', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_email', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_date', models.DateTimeField(blank=True, null=True)),
                ('customer_message', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
