# Generated by Django 6.0.2 on 2026-03-01 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedMeet', '0010_otp_patientprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='otp',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
